---
- name: Reboot Asterisk Server
  hosts: asteriskec2
  gather_facts: no
  tasks:
    - name: Reboot the Server
      reboot:

    - name: Wait for the reboot to complete
      wait_for_connection:
        connect_timeout: 10
        sleep: 5
        delay: 5
        timeout: 180

    - name: Check Date & Time
      shell: date
      register: date_time

    - name: Display Date & Time
      debug:
        msg: "Current Date & Time is : {{ date_time.stdout }}"
...
